# Generated by Django 3.2.4 on 2022-10-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='empty',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
