# Generated by Django 3.2.4 on 2022-10-06 21:17

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='image',
            field=models.ImageField(default='media/group-chat-icon.jpg', upload_to=accounts.models.get_group_image_file_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='/person_2.jpg', upload_to=accounts.models.get_image_file_path),
        ),
    ]
