# Generated by Django 3.2.4 on 2022-10-06 21:35

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221006_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='/group-chat-icon.jpg', upload_to=accounts.models.get_image_file_path),
        ),
    ]
